version: '3.8'

services:
  ecomapi:
    build:
      context: ./EcomAPI
    container_name: ecomapi
    volumes:
      - ./EcomAPI:/var/www/html
    ports:
      - "13455:80"
    depends_on:
      - mysql
    networks:
      - ecomnetwork

  mediaplayerbackend:
    build:
      context: ./MediaPlayerBackend
    container_name: mediaplayerbackend
    volumes:
      - ./MediaPlayerBackend:/var/www/html
    ports:
      - "13456:80"
    depends_on:
      - mysql
    networks:
      - ecomnetwork

  mysql:
    image: mysql:latest
    container_name: ecom-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
    ports:
      - "3316:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecomnetwork

  mediaplayerfrontend:
    build: ./MediaPlayerFrontend
    container_name: mediaplayerfrontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./MediaPlayerFrontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    networks:
      - ecomnetwork

  nginx:
    build:
      context: ./nginx
    container_name: nginx-proxy
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - ecomapi
      - mediaplayerbackend
      - mediaplayerfrontend
    networks:
      - ecomnetwork

volumes:
  mysql-data:
  node_modules:

networks:
  ecomnetwork:
    driver: bridge
