version: '3.8'

services:
  ecomapi:
    build: ./EcomAPI
    container_name: ecomapi
    ports:
      - "8000:9000" # Laravel runs on port 9000 internally
    volumes:
      - ./EcomAPI:/var/www
    networks:
      - ecomnetwork

  mediaplayerbackend:
    build: ./MediaPlayerBackend
    container_name: mediaplayerbackend
    ports:
      - "8001:9000" # Laravel runs on port 9000 internally
    volumes:
      - ./MediaPlayerBackend:/var/www
    networks:
      - ecomnetwork

  mediaplayerfrontend:
    build: ./MediaPlayerFrontend
    container_name: mediaplayerfrontend
    ports:
      - "3000:3000" # SvelteKit runs on port 3000
    volumes:
      - ./MediaPlayerFrontend:/usr/src/app
      - node_modules:/app/node_modules
    networks:
      - ecomnetwork

networks:
  ecomnetwork:
    driver: bridge
volumes:
  node_modules: {} # need to check if we i can use this better