version: '3.8'

services:
  ecomapi:
    build: ./EcomAPI
    container_name: ecomapi
    platform: linux/amd64
    ports:
      - "13445:80"
    volumes:
      - ./EcomAPI:/var/www
    networks:
      - ecomnetwork

  mediaplayerbackend:
    build: ./MediaPlayerBackend
    container_name: mediaplayerbackend
    platform: linux/amd64
    ports:
      - "13446:80"
    volumes:
      - ./MediaPlayerBackend:/var/www
    networks:
      - ecomnetwork

  mediaplayerfrontend:
    build: ./MediaPlayerFrontend
    container_name: mediaplayerfrontend
    platform: linux/amd64
    ports:
      - "3000:3000"
    volumes:
      - ./MediaPlayerFrontend:/usr/src/app
      - node_modules:/app/node_modules
    networks:
      - ecomnetwork
  
  mysql:
    image: mysql:latest
    container_name: mediaplayerbackend-db
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: rootpasswd
      MYSQL_DATABASE: mediaBackend
    ports:
      - "3316:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - ecomnetwork

networks:
  ecomnetwork:
    driver: bridge
volumes:
  node_modules: {} # need to check if we i can use this better